Code of conduct
Hitta/.github pull request #1
Opened 2020-08-03 09:35 UTC by Zakay

## Problem and solution
Our team was lacking a code of conduct document, we had our group meeting and wrote down a code of conduct that was inspired from others such as Digital Ocean.

2020-08-03 09:39 UTC, thomas-brx approved these changes
Looks great 🏅

2020-08-03 09:58 UTC, Sealos approved these changes

2020-08-03 15:06 UTC, ricardobanegas requested changes
Great COC, I added some small comments.

2020-08-03 15:06 UTC, ricardobanegas commented on CODE_OF_CONDUCT.md
> +This Code of Conduct is designed to help all of us build a pleasant, productive, and accomplished team. Our Code of Conduct is not meant to burden the team with a bunch of needless rules, or to punis
Good intro

2020-08-03 15:06 UTC, ricardobanegas commented on CODE_OF_CONDUCT.md
> +### Interjecting
I would clarify what **Interjecting** means so that non-english natives understand (I had to google it's meaning), suggestions: 

- "Understand the problem before giving feedback"
- "Avoid interruptions"

... or something in those terms.

2020-08-03 15:06 UTC, ricardobanegas commented on CODE_OF_CONDUCT.md
> +## Giving and Receiving Feedback
Minor, but either write: 

- "Giving and receiving feedback" 
- "Giving & receiving feedback"

2020-08-03 15:06 UTC, ricardobanegas commented on CODE_OF_CONDUCT.md
> +If your behavior is problematic for a colleague, work with the other party to fix the situation. A mistake is a chance to learn and teach. Use the opportunity to better the company and team. Openness
The first sentence sounds like it's "my behaviour" this is about. I would rewrite slightly to include that the problematic behaviour is either on my or my colleagues side: 

"If you find a behaviour to be problematic, then try to work with the other party to fix the situation."

2020-08-03 15:06 UTC, ricardobanegas commented on CODE_OF_CONDUCT.md
> +Honesty, integrity, and attentiveness to the team are every bit as vital as the work itself.
Should this section have it's own headline or is it a part of "Enactment"?

2020-08-04 09:08 UTC, filippalmqvist commented on CODE_OF_CONDUCT.md
> +This Code of Conduct is designed to help all of us build a pleasant, productive, and accomplished team. Our Code of Conduct is not meant to burden the team with a bunch of needless rules, or to punis
```suggestion
This Code of Conduct is designed to help all of us build a pleasant, productive, and accomplished team. Our Code of Conduct is not meant to burden the team with a bunch of needless rules, or to punish our valued employees for past behaviors. Rather, we are striving every day to make a hospitable environment for our great engineering team, especially for those who have faced more adverse working environments in the past.
```

2020-08-04 09:09 UTC, filippalmqvist commented
Looks good 💯

2020-08-10 10:26 UTC, merged